language: java
jdk:
  - openjdk8
sudo: required
services:
  - docker

cache:
  directories:
    - $HOME/.m2/

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

install:
  - docker pull coinbub/poli-daemon
  - mvn dependency:go-offline

script:
  - mvn test jacoco:report -B

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
