language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
sudo: required
services:
  - docker

cache:
  directories:
    - $HOME/.m2/

before_install:
  - docker pull coinbub/poli-daemon

script:
  - mvn test jacoco:report coveralls:report -B -DcontainerLocation=localhost:10001
